
/* This file was auto-generated by scripts_decoder.py, changes may be overwritten */
#ifndef scripts_lut_h
#define scripts_lut_h

#ifdef __cplusplus
  extern "C" {
#endif

struct avr_script_lut {
  const unsigned char *EnterProgMode;
         unsigned int  EnterProgMode_len;
  const unsigned char *EnterProgModeHvSp;
         unsigned int  EnterProgModeHvSp_len;
  const unsigned char *EnterProgModeHvSpRst;
         unsigned int  EnterProgModeHvSpRst_len;
  const unsigned char *EnterProgModeHvUpt;
         unsigned int  EnterProgModeHvUpt_len;
  const unsigned char *ExitProgMode;
         unsigned int  ExitProgMode_len;
  const unsigned char *SetSpeed;
         unsigned int  SetSpeed_len;
  const unsigned char *GetDeviceID;
         unsigned int  GetDeviceID_len;
  const unsigned char *EraseChip;
         unsigned int  EraseChip_len;
  const unsigned char *ReadProgmem;
         unsigned int  ReadProgmem_len;
  const unsigned char *WriteDataEEmem;
         unsigned int  WriteDataEEmem_len;
  const unsigned char *ReadDataEEmem;
         unsigned int  ReadDataEEmem_len;
  const unsigned char *WriteCSreg;
         unsigned int  WriteCSreg_len;
  const unsigned char *ReadCSreg;
         unsigned int  ReadCSreg_len;
  const unsigned char *WriteMem8;
         unsigned int  WriteMem8_len;
  const unsigned char *WriteMem16;
         unsigned int  WriteMem16_len;
  const unsigned char *ReadMem8;
         unsigned int  ReadMem8_len;
  const unsigned char *ReadMem16;
         unsigned int  ReadMem16_len;
  const unsigned char *ReadSIB;
         unsigned int  ReadSIB_len;
  const unsigned char *HoldInReset;
         unsigned int  HoldInReset_len;
  const unsigned char *ReleaseFromReset;
         unsigned int  ReleaseFromReset_len;

};

struct avr_script_lut* get_pickit_script(const char *partdesc);

#ifdef __cplusplus
}
#endif

#endif // scripts_lut_h
