
/* This file was auto-generated by scripts_decoder.py, changes may be overwritten */
#ifndef pickit_h
#define pickit_h

#ifdef __cplusplus
  extern "C" {
#endif

struct avr_script_lut {
  const unsigned char* EnterProgMode;
                  int  EnterProgMode_len;
  const unsigned char* EnterProgModeHvSp;
                  int  EnterProgModeHvSp_len;
  const unsigned char* EnterProgModeHvSpRst;
                  int  EnterProgModeHvSpRst_len;
  const unsigned char* EnterProgModeHvUpt;
                  int  EnterProgModeHvUpt_len;
  const unsigned char* ExitProgMode;
                  int  ExitProgMode_len;
  const unsigned char* SetSpeed;
                  int  SetSpeed_len;
  const unsigned char* GetDeviceID;
                  int  GetDeviceID_len;
  const unsigned char* EraseChip;
                  int  EraseChip_len;
  const unsigned char* ReadProgmem;
                  int  ReadProgmem_len;
  const unsigned char* WriteDataEEmem;
                  int  WriteDataEEmem_len;
  const unsigned char* ReadDataEEmem;
                  int  ReadDataEEmem_len;
  const unsigned char* WriteCSreg;
                  int  WriteCSreg_len;
  const unsigned char* ReadCSreg;
                  int  ReadCSreg_len;
  const unsigned char* WriteMem8;
                  int  WriteMem8_len;
  const unsigned char* WriteMem16;
                  int  WriteMem16_len;
  const unsigned char* ReadMem8;
                  int  ReadMem8_len;
  const unsigned char* ReadMem16;
                  int  ReadMem16_len;
  const unsigned char* ReadSIB;
                  int  ReadSIB_len;
  const unsigned char* HoldInReset;
                  int  HoldInReset_len;
  const unsigned char* ReleaseFromReset;
                  int  ReleaseFromReset_len;

};

struct avr_script_lut* get_pickit_script(const char* partdesc);

#ifdef __cplusplus
}
#endif

#endif // pickit_h
