function(buildinfo_setup)
  message(STATUS "BEGIN buildinfo_setup")
  string(CONCAT BUILDINFO_INCLUDE_TOP
    "  /* buildinfo-include.c - DO NOT MODIFY THIS FILE! */\n"
    "  /* This include file buildinfo-include.c is AUTOGENERATED by configure. */\n"
    "  /* This file is meant to be \#include'ed, but is not a header file. */\n"
  )
  file(WRITE "${CMAKE_CURRENT_BINARY_DIR}/src/buildinfo-include.c"
    "${BUILDINFO_INCLUDE_TOP}")
  string(CONCAT BUILDINFO_SUMMARY_TOP
    "\n"
    "\n"
    "Configuration summary:\n"
    "----------------------\n"
    "\n"
  )
  file(WRITE "${CMAKE_CURRENT_BINARY_DIR}/buildinfo-summary.txt"
    "${BUILDINFO_SUMMARY_TOP}")
  message(STATUS "END buildinfo_setup")
endfunction()

function(buildinfo_item KEY VAL)
  cmake_parse_arguments(arg "" "" "" ${ARGN})
  # message(STATUS "BEGIN buildinfo_item")
  # message(STATUS "  K,V: ${KEY}, ${VAL}")
  file(APPEND "${CMAKE_CURRENT_BINARY_DIR}/src/buildinfo-include.c"
    "  {\"AUTO-BUILDINFO ${KEY}\", \"${VAL}\"},\n")
  file(APPEND "${CMAKE_CURRENT_BINARY_DIR}/buildinfo-summary.txt"
    "  * ${KEY}: ${VAL}\n")
  # message(STATUS "END buildinfo_item")
endfunction()

function(buildinfo_output)
  message(STATUS "BEGIN buildinfo_output")
  file(APPEND "${CMAKE_CURRENT_BINARY_DIR}/src/buildinfo-include.c"
    "  /* end of buildinfo-include.c */\n")
  #file(APPEND "${CMAKE_CURRENT_BINARY_DIR}/buildinfo-summary.txt"
  #  "\nThe End.\n")
  file(READ "${CMAKE_CURRENT_BINARY_DIR}/buildinfo-summary.txt" msg)
  message(STATUS ${msg})
  message(STATUS "END buildinfo_output")
endfunction()

buildinfo_setup()
